version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_react
    image: image/portfolio_react
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
